version: 0.2
phases:
  build:
    commands:
      - terraform init
      - terraform workspace new "$STACK_ID"
      - |
        terraform apply \
        -var "source_version=$CODEBUILD_SOURCE_VERSION" \
        -var "environment=$ENVIRONMENT" \
        -var "stack_id=$STACK_ID" \
        -var "table_name=$TABLE_NAME" \
        -var "instance_type=$INSTANCE_TYPE" \
        -var "security_group_ids=[$SECURITY_GROUP_IDS]" \
        -var "template_name=$TEMPLATE_NAME" \
        -var "template_vars=$TEMPLATE_VARS" \
        -auto-approve
